<?php


/*
Plugin Name: Eventer
Description: An event management interface to help set up perfect events.
Plugin URI:  https://dagora.ch
Author:      Matt Bedford
Version:     2.0
License:     GPLv2 or later
License URI: https://www.gnu.org/licenses/gpl-2.0.txt

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 
2 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
with this program. If not, visit: https://www.gnu.org/licenses/


*/

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// include dependencies
require plugin_dir_path( __FILE__ ) . 'event_globals.php';

// On activate, trigger new menu class
//register_activation_hook( __FILE__, 'do_event_start_up' ); 

//function do_event_start_up() {
	
//}

//Create menu page
function do_eventer() {
	add_menu_page( 
		'Eventer',
		'Mission control',
		'manage_options',
		'eventer',
		'event_setup',
		'dashicons-admin-site-alt3', 
		1
	); 
}
add_action( 'admin_menu', 'do_eventer' );


//Callback for menu page adds only the div for vue instantiation
function event_setup() { 
	?>
	<script>
		jQuery(document).ready(function(){
			jQuery('#collapse-button').click();
		})
	</script>
	<?php
	echo "<div id='app'></div>";
}


add_action( 'admin_enqueue_scripts', 'load_vue_core' );
function load_vue_core($hook) {
	if($hook !== 'toplevel_page_eventer') return;
	wp_register_script( // the app build script generated by Webpack.
		'vue_app',
		'http://localhost:8080/js/app.js',
		//get_stylesheet_directory_uri() . '/dist/js/app.500297bd.js',
		array(),
		false,
		true
	); 
	wp_register_script( // the app build script generated by Webpack.
		'vue_chunks',
		'http://localhost:8080/js/chunk-vendors.js',
		//get_stylesheet_directory_uri() . '/dist/js/chunk-vendors.c5180c15.js',
		array(),
		false,
		true
	);
	wp_enqueue_style( 'vue_styles', plugins_url('assets/styles.css', __FILE__), array(), '');
	wp_enqueue_script('vue_app');
	wp_enqueue_script('vue_chunks');
}